language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - cd strassengezwitscher
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
  - cd ../.travis
  - openssl aes-256-cbc -K $encrypted_423a58ca66b3_key -iv $encrypted_423a58ca66b3_iv -in deploy_key.pem.enc -out deploy_key.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_key.pem
  - ssh-add deploy_key.pem
  - ./deploy.sh
