language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - cd strassengezwitscher
script:
  - coverage run --source='.' manage.py test
  - coverage report
