language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - cd strassengezwitscher
script:
  - coverage run manage.py test
after_success:
  - coveralls
